kind: ReplicationController
apiVersion: v1
metadata:
  name: jobmanager-controller
  namespace: flink
spec:
  replicas: 1
  selector:
    component: jobmanager
  template:
    metadata:
      labels:
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: melentye/flink:1.1.3-custom-akka3
          args: ["jobmanager", "jobmanager.rpc.address=jobmanager.flink.svc.cluster.local", "blob.server.port=50101"]
          ports:
            - containerPort: 6123
            - containerPort: 8081
            - containerPort: 50101
          resources:
            requests:
              cpu: 100m