kind: Service
apiVersion: v1
metadata:
  name: jobmanager-webui
  namespace: flink
spec:
  type: ClusterIP
  clusterIP: 10.91.253.10
  selector:
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: http